### ISSUE TITLE
Display wrong error message in login

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#140]
When we enter a wrong email/password, it displays a technical error instead of the proper error.
[update] Origin : /api/public/authentication/login - Error 500
https://i.gyazo.com/9290c1b04c06693a6d5865a2ef117f93.png

**Comment by s150217754** [comment]
Yup. Able to replicate this issue.  @sant0ro 

Failed login should display a "shake" animation in Red on the Login and Password field.

**Comment by sant0ro** [comment]
Thanks! Going to fix it.

**Comment by sant0ro** [comment]
Fixed. Commiting soon as possible.

**Comment by BobyTS** [comment]
This issue is back. Bad error message in login with incorrect password

**Comment by sant0ro** [comment]
Fixed.
