### ISSUE TITLE
ip_register not updating

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#56]
Hi,

As above, upon registration - **users > ip_register** remains empty and is not filled in by the CMS.

Thanks!

**Comment by sant0ro** [comment]
I already fixed it. As far i know.

**Comment by s150217754** [comment]
Hey @sant0ro ,

Problem still exist. Using development branch (commit d35b69f).

**Comment by sant0ro** [comment]
Tested here. It's working.... I don't know why isn't working with you.

**Comment by s150217754** [comment]
@sant0ro Just to ensure we're on the same page, it's **ip_register** not ip_current.

Will do a clean install and try out if your ip_register (upon registration) is updating well.

**Comment by sant0ro** [comment]
Oh, yeah, now i see.

Okay coding ip_register, wait few minutes.

**Comment by sant0ro** [comment]
Fixed it. Commiting it now.
